modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Christofmeg/MekanismCardboardTooltip/issues" #optional
license="The MIT License (MIT)"
[[mods]]
	modId="mekanismcardboardtooltip"
	version="1.1.0"
	displayName="Mekanism Cardboard Tooltip"
	displayURL="https://github.com/Christofmeg/MekanismCardboardTooltip" #optional
	#logoFile="icon.png"
	#credits=""
	authors="Christofmeg"
	description="Mekanism Cardboard Boxes + Jade = this. \nCardboard Boxes now shows what Block and Block Entity is inside. \nComes with special support for monster spawners."
[[dependencies.mekanismcardboardtooltip]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mekanismcardboardtooltip]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mekanismcardboardtooltip]]
    modId="jade"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mekanismcardboardtooltip]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.2,)"
    ordering="NONE"
    side="BOTH"
[modproperties.mekanismcardboardtooltip]
    catalogueItemIcon="mekanism:cardboard_box"
