modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Christofmeg/MekanismCardboardTooltip/issues"
license="${mod_license}"
[[mods]]
    modId="${mod_id}"
	version="${version}"
	displayName="${mod_name}"
    displayURL="https://github.com/Christofmeg/MekanismCardboardTooltip"
	authors="${mod_authors}"
	description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="jade"
    mandatory=false
    versionRange="${jade_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="mekanism"
    mandatory=true
    versionRange="${mekanism_version_range}"
    ordering="NONE"
    side="BOTH"
[modproperties.${mod_id}]
    catalogueItemIcon="mekanism:cardboard_box"
