modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Christofmeg/MekanismCardboardTooltip/issues" #optional
license="The MIT License (MIT)"
[[mods]]
	modId="mekanismcardboardtooltip"
	version="1.1.0"
	displayName="Mekanism Cardboard Tooltip"
	displayURL="https://github.com/Christofmeg/MekanismCardboardTooltip" #optional
	#logoFile="icon.png"
	#credits=""
	authors="Christofmeg"
	description="Mekanism Cardboard Boxes + Jade = this. \nCardboard Boxes now shows what Block and Block Entity is inside. \nComes with special support for monster spawners."
[[dependencies.mekanismcardboardtooltip]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mekanismcardboardtooltip]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mekanismcardboardtooltip]]
    modId="jade"
    mandatory=true
    versionRange="[2.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mekanismcardboardtooltip]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.0,)"
    ordering="NONE"
    side="BOTH"
[modproperties.mekanismcardboardtooltip]
    catalogueItemIcon="mekanism:cardboard_box"
